services:
  db:
    image: mysql:8.0
    container_name: patient-db
    restart: always
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ALIEN_DB_PW}
      MYSQL_USER: alienworkspace
      MYSQL_PASSWORD: ${ALIEN_DB_PW}
    volumes:
      - ./init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      retries: 5
      timeout: 5s
    extends:
      file: common-config.yml
      service: network-base-config

  cdr-cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cdr-cloudflared
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    extends:
      file: common-config.yml
      service: network-base-config
    environment:
      - "TUNNEL_TOKEN=${CDR_CONFIGSERVER_TUNNEL_TOKEN}"

  redis:
    image: redis
    container_name: cdr-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      retries: 10
      timeout: 5s
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-base-config

  rabbit:
    image: rabbitmq:3.12-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 10s
      retries: 10
      timeout: 5s
      start_period: 10s
    extends:
      file: common-config.yml
      service: network-base-config

  configserver:
    image: enumahin/cdr-configserver:0.0.3.SNAPSHOT
    container_name: configserver
    ports:
      - "8071:8071"
    healthcheck:
      test: "curl --fail --silent http://localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 30s
      start_period: 30s
    depends_on:
      rabbit:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: rabbit-network-base-config

  eurekaserver:
    image: enumahin/cdr-service-discovery:0.0.1-SNAPSHOT
    container_name: eurekaserver
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent http://localhost:8761/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 30s
      start_period: 30s
    depends_on:
      configserver:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: configserver-base-config
    environment:
      - SPRING_APPLICATION_NAME=eurekaserver

  gatewayserver:
    image: enumahin/cdr-edge-gateway-server:0.0.1-SNAPSHOT
    container_name: gatewayserver
    ports:
      - "9191:9191"
    depends_on:
      metadata:
        condition: service_healthy
      demographic:
        condition: service_healthy
      patient:
        condition: service_healthy
      redis:
        condition: service_healthy
    extends:
      file: common-config.yml
      service: eureka-configserver-config
    environment:
      - SPRING_APPLICATION_NAME=gatewayserver
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eurekaserver:8761/eureka
      - SPRING_DATA_REDIS_CONNECTION-TIMEOUT=2s
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_DATA_REDIS_TIMEOUT=1s

  metadata:
    image: enumahin/metadata-microservice:0.0.4.SNAPSHOT
    container_name: metadata-ms
    ports:
      - "8010:8010"
    healthcheck:
      test: "curl --fail --silent http://localhost:8010/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 30s
      start_period: 30s
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/metadata
      SPRING_APPLICATION_NAME: "metadata"
    extends:
      file: common-config.yml
      service: microservice-base-config

  patient:
    image: enumahin/patient-microservice:0.0.4.SNAPSHOT
    container_name: patient-ms
    ports:
      - "8030:8030"
    healthcheck:
      test: "curl --fail --silent http://localhost:8030/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 30s
      start_period: 30s
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/patient
      SPRING_APPLICATION_NAME: "patient"
    extends:
      file: common-config.yml
      service: microservice-base-config

  demographic:
    image: enumahin/demographic-microservice:0.0.4.SNAPSHOT
    container_name: demographic-ms
    ports:
      - "8020:8020"
    healthcheck:
      test: "curl --fail --silent http://localhost:8020/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      retries: 10
      timeout: 30s
      start_period: 30s
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demographic
      SPRING_APPLICATION_NAME: "demographic"
    extends:
      file: common-config.yml
      service: microservice-base-config

networks:
  cdr-network:
    driver: bridge
