services:
  db:
    image: mysql:8.0
    container_name: patient-db
    restart: always
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${ALIEN_DB_PW}
      MYSQL_USER: alienworkspace
      MYSQL_PASSWORD: ${ALIEN_DB_PW}
    volumes:
      - ./init/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 5s
      retries: 5
      timeout: 5s
    networks:
      - cdr-network

  metadata:
    image: enumahin/metadata-microservice:0.0.1
    container_name: metadata-ms
    ports:
      - "8010:8010"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/metadata
      SPRING_DATASOURCE_USERNAME: alienworkspace
      SPRING_DATASOURCE_PASSWORD: ${ALIEN_DB_PW}
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 700m
    networks:
      - cdr-network

  patient:
    image: enumahin/patient-microservice:0.0.1
    container_name: patient-ms
    ports:
      - "8030:8030"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/patient
      SPRING_DATASOURCE_USERNAME: alienworkspace
      SPRING_DATASOURCE_PASSWORD: ${ALIEN_DB_PW}
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 700m
    networks:
      - cdr-network

  demographic:
    image: enumahin/demographic-microservice:0.0.1-SNAPSHOT
    container_name: demographic-ms
    ports:
      - "8020:8020"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/demographic
      SPRING_DATASOURCE_USERNAME: alienworkspace
      SPRING_DATASOURCE_PASSWORD: ${ALIEN_DB_PW}
    depends_on:
      db:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 700m
    networks:
      - cdr-network

networks:
  cdr-network:
    driver: bridge
